owner: Path-of-Progress
repo: status

sites:
  - name: Path of Progress
    url: https://app.pathofprogress.ca/api/health
    expectedStatusCodes:
      - 200
  - name: Website
    url: https://www.pathofprogress.ca
    expectedStatusCodes:
      - 200
      - 301

status-website:
  baseUrl: /status
  logoUrl: https://app.pathofprogress.ca/favicon.ico
  name: Path of Progress Status
  introTitle: "**Path of Progress** service status"
  introMessage: Real-time uptime monitoring powered by [Upptime](https://github.com/upptime/upptime). If you're experiencing issues, check below for current status.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
